# Curated, fact-checked local detail for well-known major US cities.
# Keyed by (state_id, city_ascii). Only include neighborhoods/landmarks we are
# confident are real -- never invent specifics for cities not listed here.
# Format: (neighborhoods_tuple, landmarks_tuple)

CURATED = {
    ("NY", "New York"): (("Brooklyn", "Queens", "the Bronx", "Harlem", "Staten Island"),
        ("Central Park", "the Brooklyn Bridge", "the Hudson River waterfront")),
    ("CA", "Los Angeles"): (("Hollywood", "Venice", "Silver Lake", "Echo Park", "the San Fernando Valley"),
        ("Griffith Park", "the Hollywood Sign", "the Los Angeles River")),
    ("IL", "Chicago"): (("Wicker Park", "Lincoln Park", "Hyde Park", "the South Loop"),
        ("Lake Michigan", "Millennium Park", "the Chicago River")),
    ("TX", "Houston"): (("The Heights", "Midtown", "River Oaks", "Spring Branch"),
        ("Buffalo Bayou", "Hermann Park", "the Houston Ship Channel")),
    ("AZ", "Phoenix"): (("Arcadia", "Ahwatukee", "Encanto", "Desert Ridge"),
        ("South Mountain Park", "Camelback Mountain", "the Salt River")),
    ("PA", "Philadelphia"): (("South Philly", "Fishtown", "Manayunk", "Germantown"),
        ("Fairmount Park", "the Schuylkill River", "Independence Hall")),
    ("TX", "San Antonio"): (("Alamo Heights", "Stone Oak", "Southtown"),
        ("the River Walk", "the Alamo", "Brackenridge Park")),
    ("CA", "San Diego"): (("La Jolla", "Pacific Beach", "North Park", "Mission Valley"),
        ("Balboa Park", "Mission Bay", "the San Diego River")),
    ("TX", "Dallas"): (("Uptown", "Oak Cliff", "Lakewood", "Deep Ellum"),
        ("White Rock Lake", "the Trinity River", "Klyde Warren Park")),
    ("TX", "Austin"): (("South Congress", "East Austin", "Zilker", "The Domain"),
        ("Lady Bird Lake", "Barton Springs", "Zilker Park")),
    ("FL", "Jacksonville"): (("Riverside", "San Marco", "Mandarin", "the Southside"),
        ("the St. Johns River", "Jacksonville Beach")),
    ("TX", "Fort Worth"): (("Sundance Square area", "Cultural District", "TCU area"),
        ("the Trinity River", "the Fort Worth Stockyards")),
    ("OH", "Columbus"): (("German Village", "Short North", "Clintonville"),
        ("the Scioto River", "Ohio State University campus")),
    ("NC", "Charlotte"): (("NoDa", "South End", "Dilworth", "Ballantyne"),
        ("Freedom Park", "the Catawba River nearby")),
    ("CA", "San Francisco"): (("the Mission", "Sunset District", "Richmond District", "Noe Valley"),
        ("Golden Gate Park", "the Golden Gate Bridge", "the Bay waterfront")),
    ("IN", "Indianapolis"): (("Broad Ripple", "Fountain Square", "Irvington"),
        ("White River State Park", "the Indianapolis Motor Speedway")),
    ("WA", "Seattle"): (("Capitol Hill", "Ballard", "Fremont", "West Seattle"),
        ("Lake Washington", "Puget Sound", "Discovery Park")),
    ("CO", "Denver"): (("LoDo", "Highlands", "Cherry Creek", "Stapleton/Central Park"),
        ("the South Platte River", "Cheesman Park")),
    ("DC", "Washington"): (("Georgetown", "Capitol Hill", "Adams Morgan", "Anacostia"),
        ("the Potomac River", "Rock Creek Park", "the National Mall")),
    ("MA", "Boston"): (("Back Bay", "South Boston", "Jamaica Plain", "Dorchester"),
        ("the Charles River", "Boston Common")),
    ("TN", "Nashville"): (("East Nashville", "12 South", "Germantown", "Belle Meade"),
        ("the Cumberland River", "Centennial Park")),
    ("MI", "Detroit"): (("Corktown", "Midtown", "Grosse Pointe area", "Southwest Detroit"),
        ("the Detroit River", "Belle Isle Park")),
    ("OR", "Portland"): (("Alberta Arts District", "Hawthorne", "Pearl District", "Sellwood"),
        ("the Willamette River", "Forest Park")),
    ("TN", "Memphis"): (("Midtown", "Cooper-Young", "Downtown/South Main"),
        ("the Mississippi River", "Overton Park")),
    ("NV", "Las Vegas"): (("Summerlin", "Henderson border area", "the Arts District"),
        ("the Las Vegas Strip nearby", "Red Rock Canyon")),
    ("KY", "Louisville"): (("Highlands", "St. Matthews", "Old Louisville"),
        ("the Ohio River", "Cherokee Park")),
    ("MD", "Baltimore"): (("Fells Point", "Canton", "Federal Hill", "Hampden"),
        ("the Inner Harbor", "the Patapsco River")),
    ("WI", "Milwaukee"): (("Bay View", "Riverwest", "the Third Ward"),
        ("Lake Michigan", "the Milwaukee River")),
    ("NM", "Albuquerque"): (("Nob Hill", "Old Town", "the North Valley"),
        ("the Rio Grande", "the Sandia Mountains")),
    ("AZ", "Tucson"): (("Sam Hughes", "the Foothills", "Barrio Viejo"),
        ("the Santa Catalina Mountains", "Saguaro National Park nearby")),
    ("CA", "Fresno"): (("Tower District", "Woodward Park area"),
        ("Woodward Park", "the San Joaquin River")),
    ("CA", "Sacramento"): (("Midtown", "East Sacramento", "Land Park"),
        ("the American River", "the Sacramento River", "Old Sacramento")),
    ("AZ", "Mesa"): (("Downtown Mesa", "Dobson Ranch"),
        ("the Salt River", "Usery Mountain Regional Park nearby")),
    ("GA", "Atlanta"): (("Midtown", "Buckhead", "Old Fourth Ward", "Inman Park"),
        ("Piedmont Park", "the Atlanta BeltLine")),
    ("MO", "Kansas City"): (("Westport", "the Country Club Plaza", "River Market"),
        ("the Missouri River", "Swope Park")),
    ("CO", "Colorado Springs"): (("Old Colorado City", "Broadmoor area"),
        ("Garden of the Gods", "Pikes Peak nearby")),
    ("FL", "Miami"): (("Wynwood", "Little Havana", "Coconut Grove", "Brickell"),
        ("Biscayne Bay", "Vizcaya Museum and Gardens")),
    ("NC", "Raleigh"): (("Five Points", "North Hills", "Oakwood"),
        ("Pullen Park", "the Neuse River nearby")),
    ("NE", "Omaha"): (("Dundee", "Benson", "the Old Market"),
        ("the Missouri River", "Heartland of America Park")),
    ("CA", "Long Beach"): (("Belmont Shore", "Naples", "Bixby Knolls"),
        ("the Long Beach waterfront", "El Dorado Park")),
    ("VA", "Virginia Beach"): (("the Oceanfront", "Great Neck", "Kempsville"),
        ("the Atlantic shoreline", "Mount Trashmore Park")),
    ("CA", "Oakland"): (("Rockridge", "Lake Merritt area", "Fruitvale"),
        ("Lake Merritt", "the Oakland Hills")),
    ("MN", "Minneapolis"): (("Uptown", "Northeast Minneapolis", "Powderhorn"),
        ("the Mississippi River", "the Chain of Lakes")),
    ("OK", "Tulsa"): (("Cherry Street", "Brookside", "Kendall-Whittier"),
        ("the Arkansas River", "Woodward Park")),
    ("FL", "Tampa"): (("Hyde Park", "Ybor City", "Seminole Heights"),
        ("Tampa Bay", "the Hillsborough River")),
    ("TX", "Arlington"): (("Downtown Arlington", "Viridian"),
        ("Lake Arlington", "the AT&T Stadium area")),
    ("LA", "New Orleans"): (("the French Quarter", "Garden District", "Uptown", "Bywater"),
        ("the Mississippi River", "Lake Pontchartrain")),
    ("KS", "Wichita"): (("College Hill", "Riverside", "Delano"),
        ("the Arkansas River", "Sedgwick County Park nearby")),
    ("OH", "Cleveland"): (("Ohio City", "Tremont", "Detroit-Shoreway"),
        ("Lake Erie", "the Cuyahoga River")),
    ("CA", "Bakersfield"): (("Downtown Bakersfield", "Seven Oaks"),
        ("the Kern River", "the San Joaquin Valley")),
    ("CO", "Aurora"): (("Southlands area", "Havana Street corridor"),
        ("Cherry Creek State Park nearby", "the Aurora Reservoir")),
    ("CA", "Anaheim"): (("the Anaheim Resort District", "Anaheim Hills"),
        ("Angel Stadium area", "the Santa Ana River")),
    ("HI", "Honolulu"): (("Waikiki", "Manoa", "Kaimuki"),
        ("Diamond Head", "the Pacific shoreline")),
    ("CA", "Santa Ana"): (("Downtown Santa Ana", "French Park"),
        ("the Santa Ana River", "Santiago Creek")),
    ("CA", "Riverside"): (("Downtown Riverside", "Wood Streets"),
        ("the Santa Ana River", "Mount Rubidoux")),
    ("TX", "Corpus Christi"): (("the Bayfront", "Padre Island area"),
        ("Corpus Christi Bay", "the Gulf of Mexico shoreline")),
    ("KY", "Lexington"): (("Chevy Chase", "the Distillery District"),
        ("Kentucky Horse Park nearby", "the Bluegrass region horse farms")),
    ("CA", "Stockton"): (("Lincoln Village", "the Miracle Mile"),
        ("the San Joaquin River Delta", "Victory Park")),
    ("NV", "Henderson"): (("Green Valley", "Anthem"),
        ("Lake Las Vegas nearby", "the Sloan Canyon area")),
    ("MN", "Saint Paul"): (("Summit Hill", "Grand Avenue", "Highland Park"),
        ("the Mississippi River", "Como Park")),
    ("MO", "St. Louis"): (("the Central West End", "Soulard", "the Delmar Loop"),
        ("the Gateway Arch", "the Mississippi River", "Forest Park")),
    ("OH", "Cincinnati"): (("Over-the-Rhine", "Hyde Park", "Mount Adams"),
        ("the Ohio River", "Eden Park")),
    ("PA", "Pittsburgh"): (("Shadyside", "Lawrenceville", "the South Side"),
        ("the confluence of the Allegheny and Monongahela Rivers", "Schenley Park")),
    ("NC", "Greensboro"): (("Fisher Park", "Irving Park"),
        ("Lake Daniel Park", "the Guilford Courthouse battlefield")),
    ("AK", "Anchorage"): (("Downtown Anchorage", "South Addition", "Eagle River area"),
        ("the Chugach Mountains", "Cook Inlet")),
    ("TX", "Plano"): (("Legacy West", "Downtown Plano"),
        ("Oak Point Park", "the Bob Woodruff Park area")),
    ("NE", "Lincoln"): (("the Near South neighborhood", "Haymarket District"),
        ("Pioneers Park", "the Salt Creek")),
    ("FL", "Orlando"): (("Winter Park border", "College Park", "Thornton Park"),
        ("Lake Eola Park", "the theme park corridor nearby")),
    ("CA", "Irvine"): (("Woodbridge", "the Great Park neighborhood"),
        ("the Orange County Great Park", "the San Joaquin Marsh")),
    ("NJ", "Newark"): (("the Ironbound", "Forest Hill"),
        ("Branch Brook Park", "the Passaic River")),
    ("OH", "Toledo"): (("Old West End", "the Warehouse District"),
        ("the Maumee River", "Lake Erie nearby")),
    ("NC", "Durham"): (("Ninth Street", "Trinity Park", "the American Tobacco District"),
        ("Duke University campus", "Eno River State Park nearby")),
    ("FL", "St. Petersburg"): (("Old Northeast", "the Grand Central District"),
        ("Tampa Bay", "the Gulf of Mexico shoreline")),
    ("TX", "Laredo"): (("Downtown Laredo",),
        ("the Rio Grande",)),
    ("WI", "Madison"): (("the Isthmus", "Williamson Street"),
        ("Lake Mendota", "Lake Monona")),
    ("AZ", "Chandler"): (("Downtown Chandler", "Ocotillo"),
        ("the Sonoran Desert", "the Price Corridor")),
    ("NY", "Buffalo"): (("Elmwood Village", "the Old First Ward"),
        ("Lake Erie", "the Buffalo River", "Niagara Falls nearby")),
    ("AZ", "Scottsdale"): (("Old Town Scottsdale", "DC Ranch"),
        ("the McDowell Sonoran Preserve", "Camelback Mountain nearby")),
    ("NV", "Reno"): (("Midtown Reno", "the Old Southwest"),
        ("the Truckee River", "the Sierra Nevada foothills")),
    ("VA", "Norfolk"): (("Ghent", "Ocean View"),
        ("the Elizabeth River", "the Chesapeake Bay")),
    ("TX", "Irving"): (("Las Colinas", "Valley Ranch"),
        ("Lake Carolyn", "the Trinity River")),
    ("VA", "Chesapeake"): (("Great Bridge", "Western Branch"),
        ("the Great Dismal Swamp nearby", "the Elizabeth River")),
    ("FL", "Hialeah"): (("Palm Springs North area",),
        ("the Miami Canal",)),
    ("LA", "Baton Rouge"): (("Garden District", "Spanish Town"),
        ("the Mississippi River", "LSU campus")),
    ("VA", "Richmond"): (("the Fan District", "Church Hill", "Carytown"),
        ("the James River", "Maymont Park")),
    ("ID", "Boise"): (("the North End", "Downtown Boise"),
        ("the Boise River Greenbelt", "the Boise Foothills")),
    ("AL", "Birmingham"): (("Five Points South", "Forest Park"),
        ("Red Mountain", "Railroad Park")),
    ("WA", "Spokane"): (("South Hill", "Browne's Addition"),
        ("the Spokane River", "Riverfront Park")),
    ("NY", "Rochester"): (("Park Avenue neighborhood", "the East End"),
        ("the Genesee River", "Lake Ontario nearby")),
    ("UT", "Salt Lake City"): (("the Avenues", "Sugar House"),
        ("the Wasatch Range", "the Jordan River")),
    ("FL", "Tallahassee"): (("Midtown Tallahassee", "Betton Hills"),
        ("Lake Ella", "the Apalachicola National Forest nearby")),
    ("TN", "Knoxville"): (("Old City", "Sequoyah Hills"),
        ("the Tennessee River", "the Great Smoky Mountains nearby")),
    ("RI", "Providence"): (("Federal Hill", "College Hill"),
        ("the Providence River", "Roger Williams Park")),
    ("TN", "Chattanooga"): (("the Southside", "North Shore"),
        ("the Tennessee River", "Lookout Mountain nearby")),
    ("FL", "Fort Lauderdale"): (("Las Olas", "Victoria Park"),
        ("the New River", "the Atlantic shoreline")),
    ("SC", "Columbia"): (("Five Points", "Shandon"),
        ("the Congaree River", "Riverfront Park")),
    ("SC", "Charleston"): (("the Historic District", "West Ashley"),
        ("the Charleston Harbor", "the Battery")),
    ("GA", "Savannah"): (("the Historic District", "Ardsley Park"),
        ("Forsyth Park", "the Savannah River")),
    ("CT", "Hartford"): (("West End", "Frog Hollow"),
        ("the Connecticut River", "Bushnell Park")),
    ("CT", "New Haven"): (("East Rock", "Westville"),
        ("Yale University campus", "New Haven Harbor")),
}
